### PR TITLE
No need to upgrade authSchema when starting with a new 3.0+ installation

### PR DESCRIPTION
**Pull request by ghost**
A PR regarding issue #18 .

### CODE REVIEW

**Comment by knutole** [comment]
This is perhaps not compatible with older versions, still? What will happen if Mongo is < 3.0 ?

**Comment by ghost** [comment]
Yeah, I believe it will not work.
I will create another PR which includes back compatibility solution.

**Comment by knutole** [comment]
@mirzahusadzic  Having tested a bit, I think the backwards comp is not important and this PR could be merged. I can't merge this now, because the branch is deleted. If you could please reopen this, @mirzahusadzic, I will merge this on your name.

Thanks!

**Comment by ghost** [comment]
@knutole I restored the branch! Thanks!

**Comment by knutole** [comment]
Thanks, merged! 👍 Can you send me your Github registered email, so I can add you properly to the commit history? You can send it to my email knutole at mapic dot io if you like. Thanks again!

**Pull request merged**
